### ISSUE TITLE
老哥，有没有写过一篇 celery的文章

### ISSUE THREAD

**Issue by mlzboy** [itnotebooks/cert_manage#14]
[基于Django+celery配置定时任务：重写celery Task页面 - Eric](https://www.itnotebooks.com/?p=369)，如果是的话，这篇 文章 有没有留底呢，网上找不到了，冒昧打扰

**Comment by ericwinn** [comment]
页面恢复了

**Comment by ericwinn** [comment]
https://www.itnotebooks.com/?p=369
